version: "3"

services:

  nginx:
    image: nginx:1.15.2-alpine
    restart: always
    ports:
      - 85:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/entrypoint.sh:/entrypoint.sh
    command: /entrypoint.sh

  server:
    # TODO: Make production image.
    restart: always
    command: make run

  db:
    image: postgres:10.5
    restart: always
